name: "covergates actions"
description: "push coverage report to covergates"
inputs:
  report-id:
    description: "covergates report id of your repository"
    required: true
  report-type:
    description: "coverage report type"
    required: true
  report-file:
    description: "coverage report file path"
    default: "./"
    required: true
  pull-request:
    description: "leave comment on pull request or not"
    required: false
    default: ""
runs:
  using: composite
  run: |
    CGO_ENABLED=1 go build -v -o /bin/covergates -ldflags="-X main.CoverGatesAPI=https://covergates.com/api/v1" ./cmd/cli
    ${{ github.action_path }}/covergates.sh ${{ inputs.report-id }} ${{ inputs.report-type }} ${{ inputs.report-file }} ${{ inputs.pull-request }}
