name: Main
on: [pull_request]
jobs:
  covergates:
    runs-on: ubuntu-latest
    name: Covergates
    steps:
      - name: report
        uses: covergates/github-actions@v0.2
        with:
          report-id: "bsinj7a23akg009ii0u0"
          report-type: "go"
          report-file: "./testdata/coverage.out"
          pull-request: "true"
