name: Main
on: [pull_request]
jobs:
  covergates:
    runs-on: ubuntu-latest
    name: Covergates
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Report
        uses: laojianzi/github-actions@v1
        with:
          report-id: "bsinj7a23akg009ii0u0"
          report-type: "go"
          report-file: "./testdata/coverage.out"
          pull-request: "true"
